-- 이 후보를 어느 정렬기가 냈는지 적는다.
--
-- 검정치마 EVERYTHING 은 받아쓰기가 C++ 단언에서 깨져 노래 정렬기가 죽었고, 조용히 옛 whisperx
-- 로 물러섰다. 그렇게 나온 타이밍이 품질 0.96 을 달고 자동 공개됐다 — 34곡 중 3곡이 그랬는데
-- 로그에만 남아서, 사람이 곡을 듣고 「최악」이라고 말하기 전까지 아무도 몰랐다.
--
-- 'sung'     노래로 학습한 정렬기가 끝까지 갔다.
-- 'whisperx' 애초에 그 길이 아니었다(한국어가 아니거나 무게가 없다) — 정상이다.
-- 'fallback' 노래 정렬기로 가다가 죽어서 물러섰다 — 사람이 들어 봐야 한다.
-- 'unknown'  이 칸이 생기기 전에 만들어진 후보.
ALTER TABLE alignment_candidates ADD COLUMN aligner TEXT NOT NULL DEFAULT 'unknown';
